// frameworks/solid-start/src/routes/users/[id].tsx
import type { JSX, Resource } from 'solid-js';
import { createResource, Show } from 'solid-js';
import type { RouteDataArgs } from 'solid-start';
import { useRouteData } from 'solid-start';
import fetchAPI from '../../lib/api';

interface IUser {
  error: string;
  id: string;
  created: string;
  karma: number;
  about: string;
}

export const routeData = (props: RouteDataArgs): Resource<IUser> => {
  const [user] = createResource<IUser, string>(
    () => `user/${props.params.id}`,
    fetchAPI<IUser>,
  );
  return user;
};

function User(): JSX.Element {
  const user = useRouteData<typeof routeData>();
  return (
    <div class="user-view">
      <Show when={user()}>
        <Show when={!user()!.error} fallback={<h1>User not found.</h1>}>
          <h1>
            User :
            {' '}
            {user()!.id}
          </h1>
          <ul class="meta">
            <li>
              <span class="label">Created:</span>
              {' '}
              {user()!.created}
            </li>
            <li>
              <span class="label">Karma:</span>
              {' '}
              {user()!.karma}
            </li>
            <Show when={user()!.about}>
              <li innerHTML={user()!.about} class="about" />
              {' '}
            </Show>
          </ul>
          <p class="links">
            <a href={`https://news.ycombinator.com/submitted?id=${user()!.id}`}>
              submissions
            </a>
            {' '}
            |
            {' '}
            <a href={`https://news.ycombinator.com/threads?id=${user()!.id}`}>
              comments
            </a>
          </p>
        </Show>
      </Show>
    </div>
  );
}

export default User;

// frameworks/next-app/app/users/[id]/page.tsx
import type { JSX } from 'react';
import fetchAPI from '../../../lib/api';

interface IUser {
  error: string;
  id: string;
  created: string;
  karma: number;
  about: string;
}

async function User({ params }: { params: { id: string } }): Promise<JSX.Element> {
  const user = await fetchAPI<IUser>(`user/${params.id}`);
  return (
    <div className="user-view">
      {
        user.error
          ? <h1>User not found.</h1>
          : (
            <>
              <h1>
                User :
                {' '}
                {user.id}
              </h1>
              <ul className="meta">
                <li>
                  <span className="label">Created:</span>
                  {' '}
                  {user.created}
                </li>
                <li>
                  <span className="label">Karma:</span>
                  {' '}
                  {user.karma}
                </li>
                {!!user.about && (
                <>
                  <li dangerouslySetInnerHTML={{ __html: user.about }} className="about" />
                  {' '}
                </>
                )}
              </ul>
              <p className="links">
                <a href={`https://news.ycombinator.com/submitted?id=${user.id}`}>
                  submissions
                </a>
                {' '}
                |
                {' '}
                <a href={`https://news.ycombinator.com/threads?id=${user.id}`}>
                  comments
                </a>
              </p>
            </>
          )
      }
    </div>
  );
}

export default User;
