// frameworks/remix/app/root.tsx
import { useEffect, type JSX } from 'react';
import { cssBundleHref } from '@remix-run/css-bundle';
import type { LinksFunction } from '@remix-run/node';
import {
  Links,
  LiveReload,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
} from '@remix-run/react';
import Nav from '../components/Nav';
import styles from '../lib/root.css';
import measure from '../lib/measure';

export const links: LinksFunction = () => [
  ...(cssBundleHref ? [{ rel: 'stylesheet', href: cssBundleHref }] : []),
  { rel: 'stylesheet', href: styles },
];

export default function App(): JSX.Element {
  useEffect(() => {
    measure();
  }, []);
  return (
    <html lang="en">
      <head>
        <title>Hacker News Clone</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Hacker News Clone" />
        <Meta />
        <Links />
      </head>
      <body>
        <Nav />
        <Outlet />
        <ScrollRestoration />
        <Scripts />
        <LiveReload />
      </body>
    </html>
  );
}

// frameworks/solid-start/src/root.tsx
// @refresh reload
import type { JSX } from 'solid-js';
import { Suspense, createEffect } from 'solid-js';
import {
  Body,
  ErrorBoundary,
  FileRoutes,
  Head,
  Html,
  Meta,
  Routes,
  Scripts,
  Title,
} from 'solid-start';
import Nav from './components/nav';
import './root.css';
import measure from './lib/measure';

export default function Root(): JSX.Element {
  createEffect(() => {
    measure();
  });
  return (
    <Html lang="en">
      <Head>
        <Title>Hacker News Clone</Title>
        <Meta charset="utf-8" />
        <Meta name="viewport" content="width=device-width, initial-scale=1" />
        <Meta name="description" content="Hacker News Clone" />
      </Head>
      <Body>
        <Nav />
        <ErrorBoundary>
          <Suspense fallback={<div class="news-list-nav">Loading...</div>}>
            <Routes>
              <FileRoutes />
            </Routes>
          </Suspense>
        </ErrorBoundary>
        <Scripts />
      </Body>
    </Html>
  );
}
