// frameworks/solid-start/src/routes/stories/[id].tsx
import type { JSX, Resource } from 'solid-js';
import { createResource, For, Show } from 'solid-js';
import type { RouteDataArgs } from 'solid-start';
import { A, useRouteData } from 'solid-start';
import Comment from '../../components/comment';
import fetchAPI, { getSpecialData } from '../../lib/api';
import type { IStory } from '../../types';

export const routeData = (props: RouteDataArgs): Resource<IStory> => {
  const [story] = createResource<IStory, string>(
    () => `item/${props.params.id}`,
    async (id) => {
      if (id === 'item/special') {
        return getSpecialData();
      }
      return fetchAPI<IStory>(id);
    },
  );
  return story;
};

function Story(): JSX.Element {
  const story = useRouteData<typeof routeData>();
  return (
    <Show when={story()}>
      <div class="item-view">
        <div class="item-view-header">
          <a href={story()!.url} target="_blank" rel="noreferrer">
            <h1>{story()!.title}</h1>
          </a>
          <Show when={story()!.domain}>
            <span class="host">
              (
              {story()!.domain}
              )
            </span>
          </Show>
          <p class="meta">
            {story()!.points}
            {' '}
            points | by
            {' '}
            <A href={`/users/${story()!.user}`}>{story()!.user}</A>
            {' '}
            {story()!.time_ago}
            {' '}
            ago
          </p>
        </div>
        <div class="item-view-comments">
          <p class="item-view-comments-header">
            {story()!.comments_count
              ? `${story()!.comments_count} comments`
              : 'No comments yet.'}
          </p>
          <ul class="comment-children">
            <For each={story()!.comments}>
              {(comment): JSX.Element => <Comment comment={comment} />}
            </For>
          </ul>
        </div>
      </div>
    </Show>
  );
}

export default Story;

// frameworks/next-app/app/stories/[id]/page.tsx
import type { JSX } from 'react';
import Link from 'next/link';
import fetchAPI, { getSpecialData } from '../../../lib/api';
import type { IStory } from '../../../components/types';
import Comment from '../../../components/Comment';

async function Story({ params }: { params: { id: string } }): Promise<JSX.Element> {
  const story = params.id === 'special'
    ? await getSpecialData()
    : await fetchAPI<IStory>(`item/${params.id}`);
  return (
    <div className="item-view">
      <div className="item-view-header">
        <a href={story.url} target="_blank" rel="noreferrer">
          <h1>{story.title}</h1>
        </a>
        {!!story.domain && (
          <span className="host">
            (
            {story.domain}
            )
          </span>
        )}
        <p className="meta">
          {story.points}
          {' '}
          points | by
          {' '}
          <Link href={`/users/${story.user}`}>{story.user}</Link>
          {' '}
          {story.time_ago}
          {' '}
          ago
        </p>
      </div>
      <div className="item-view-comments">
        <p className="item-view-comments-header">
          {story.comments_count
            ? `${story.comments_count} comments`
            : 'No comments yet.'}
        </p>
        <ul className="comment-children">
          {story.comments.map((comment) => (
            <Comment key={comment.id} comment={comment} />
          ))}
        </ul>
      </div>
    </div>
  );
}

export default Story;
