// frameworks/qwikcity/src/components/Toggle.tsx
import { Slot, component$, useSignal } from '@builder.io/qwik';

const Toggle = component$(() => {
  const open = useSignal(true);

  return (
    <>
      <div class={`toggle ${open.value ? 'open' : ''}`}>
        <button
          type="button"
          onClick$={(): void => {
            open.value = !open.value;
          }}
        >
          {open.value ? '[-]' : '[+] comments collapsed'}
        </button>
      </div>
      <ul
        class="comment-children"
        style={{ display: open.value ? 'block' : 'none' }}
      >
        <Slot />
      </ul>
    </>
  );
});

export default Toggle;

// frameworks/remix/components/Toggle.tsx
import type { ReactNode } from 'react';
import { useState } from 'react';

export default function Toggle({ children }: { children: ReactNode }): JSX.Element {
  const [open, setOpen] = useState(true);

  return (
    <>
      <div className={`toggle ${open ? 'open' : ''}`}>
        <button
          type="button"
          onClick={(): void => {
            setOpen((o) => !o);
          }}
        >
          {open ? '[-]' : '[+] comments collapsed'}
        </button>
      </div>
      <ul
        className="comment-children"
        style={{ display: open ? 'block' : 'none' }}
      >
        {children}
      </ul>
    </>
  );
}
