// frameworks/qwikcity/src/routes/[...stories]/index.tsx
import { Link, routeLoader$ } from '@builder.io/qwik-city';
import type { JSX } from '@builder.io/qwik/jsx-runtime';
import { component$ } from '@builder.io/qwik';
import fetchAPI from '../../lib/api';
import type { IStory } from '../../components/types';
import Story from '../../components/Story';

const mapStories = {
  top: 'news',
  new: 'newest',
  show: 'show',
  ask: 'ask',
  job: 'jobs',
} as const;

type MapStories = keyof typeof mapStories;

export const useData = routeLoader$(async (event) => {
  const currentPage = event.query.get('page');
  const page = currentPage ? +currentPage : 1;
  const type = (event.params.stories ? event.params.stories[0] : 'top') as MapStories;
  const stories = await fetchAPI<IStory[]>(`${mapStories[type]}?page=${page}`);
  return {
    stories,
    page,
    type,
  };
});

export default component$(() => {
  const data = useData();
  return (
    <div class="news-view">
      <div class="news-list-nav">
        {(
          data.value.page > 1
            ? (
              <Link
                class="page-link"
                href={`/${data.value.type}?page=${data.value.page - 1}`}
                aria-label="Previous Page"
              >
                {'<'}
                {' '}
                prev
              </Link>
            )
            : (
              <span class="page-link disabled" aria-disabled="true">
                {'<'}
                {' '}
                prev
              </span>
            )
        )}
        <span>
          page
          {' '}
          {data.value.page}
        </span>
        {(
          data.value.stories.length >= 29
            ? (
              <Link
                class="page-link"
                href={`/${data.value.type}?page=${data.value.page + 1}`}
                aria-label="Next Page"
              >
                more
                {' '}
                {'>'}
              </Link>
            )
            : (
              <span class="page-link disabled" aria-disabled="true">
                more
                {' '}
                {'>'}
              </span>
            )
        )}
      </div>
      <main class="news-list">
        <ul>
          {data.value.stories.map((story): JSX.Element => <Story key={story.id} story={story} />)}
        </ul>
      </main>
    </div>
  );
});

// frameworks/solid-start/src/routes/[...stories].tsx
import type { JSX, Resource } from 'solid-js';
import { createResource, For, Show } from 'solid-js';
import type { RouteDataArgs } from 'solid-start';
import { A, useRouteData } from 'solid-start';
import Story from '../components/story';
import fetchAPI from '../lib/api';
import type { IStory } from '../types';

const mapStories = {
  top: 'news',
  new: 'newest',
  show: 'show',
  ask: 'ask',
  job: 'jobs',
} as const;

type MapStories = keyof typeof mapStories;

interface Data {
  type: () => MapStories;
  page: () => number;
  stories: Resource<IStory[]>;
}

export const routeData = ({ location, params }: RouteDataArgs): Data => {
  const page = (): number => +location.query.page || 1;
  const type = (): MapStories => (params.stories || 'top') as MapStories;

  const [stories] = createResource<IStory[], string>(
    () => `${mapStories[type()]}?page=${page()}`,
    fetchAPI<IStory[]>,
  );

  return { type, stories, page };
};

function Stories(): JSX.Element {
  const { page, type, stories } = useRouteData<typeof routeData>();
  return (
    <div class="news-view">
      <div class="news-list-nav">
        <Show
          when={page() > 1}
          fallback={(
            <span class="page-link disabled" aria-disabled="true">
              {'<'}
              {' '}
              prev
            </span>
          )}
        >
          <A
            class="page-link"
            href={`/${type()}?page=${page() - 1}`}
            aria-label="Previous Page"
          >
            {'<'}
            {' '}
            prev
          </A>
        </Show>
        <span>
          page
          {' '}
          {page()}
        </span>
        <Show
          when={stories() && stories()!.length >= 29}
          fallback={(
            <span class="page-link disabled" aria-disabled="true">
              more
              {' '}
              {'>'}
            </span>
          )}
        >
          <A
            class="page-link"
            href={`/${type()}?page=${page() + 1}`}
            aria-label="Next Page"
          >
            more
            {' '}
            {'>'}
          </A>
        </Show>
      </div>
      <main class="news-list">
        <Show when={stories()}>
          <ul>
            <For each={stories()}>{(story): JSX.Element => <Story story={story} />}</For>
          </ul>
        </Show>
      </main>
    </div>
  );
}

export default Stories;
