// frameworks/next-app/app/stories/[id]/page.tsx
import type { JSX } from 'react';
import Link from 'next/link';
import fetchAPI, { getSpecialData } from '../../../lib/api';
import type { IStory } from '../../../components/types';
import Comment from '../../../components/Comment';

async function Story({ params }: { params: { id: string } }): Promise<JSX.Element> {
  const story = params.id === 'special'
    ? await getSpecialData()
    : await fetchAPI<IStory>(`item/${params.id}`);
  return (
    <div className="item-view">
      <div className="item-view-header">
        <a href={story.url} target="_blank" rel="noreferrer">
          <h1>{story.title}</h1>
        </a>
        {!!story.domain && (
          <span className="host">
            (
            {story.domain}
            )
          </span>
        )}
        <p className="meta">
          {story.points}
          {' '}
          points | by
          {' '}
          <Link href={`/users/${story.user}`}>{story.user}</Link>
          {' '}
          {story.time_ago}
          {' '}
          ago
        </p>
      </div>
      <div className="item-view-comments">
        <p className="item-view-comments-header">
          {story.comments_count
            ? `${story.comments_count} comments`
            : 'No comments yet.'}
        </p>
        <ul className="comment-children">
          {story.comments.map((comment) => (
            <Comment key={comment.id} comment={comment} />
          ))}
        </ul>
      </div>
    </div>
  );
}

export default Story;

// frameworks/qwikcity/src/routes/stories/[id]/index.tsx
import { component$ } from '@builder.io/qwik';
import { Link, routeLoader$ } from '@builder.io/qwik-city';
import fetchAPI, { getSpecialData } from '../../../lib/api';
import type { IStory } from '../../../components/types';
import Comment from '../../../components/Comment';

export const useData = routeLoader$(async (event) => (
  event.params.id === 'special'
    ? await getSpecialData()
    : await fetchAPI<IStory>(`item/${event.params.id}`)
));

export default component$(() => {
  const story = useData();
  return (
    <div class="item-view">
      <div class="item-view-header">
        <a href={story.value.url} target="_blank" rel="noreferrer">
          <h1>{story.value.title}</h1>
        </a>
        {!!story.value.domain && (
          <span class="host">
            (
            {story.value.domain}
            )
          </span>
        )}
        <p class="meta">
          {story.value.points}
          {' '}
          points | by
          {' '}
          <Link href={`/users/${story.value.user}`}>{story.value.user}</Link>
          {' '}
          {story.value.time_ago}
          {' '}
          ago
        </p>
      </div>
      <div class="item-view-comments">
        <p class="item-view-comments-header">
          {story.value.comments_count
            ? `${story.value.comments_count} comments`
            : 'No comments yet.'}
        </p>
        <ul class="comment-children">
          {story.value.comments.map((comment) => (
            <Comment key={comment.id} comment={comment} />
          ))}
        </ul>
      </div>
    </div>
  );
});
