// frameworks/solid-start/src/root.tsx
// @refresh reload
import type { JSX } from 'solid-js';
import { Suspense, createEffect } from 'solid-js';
import {
  Body,
  ErrorBoundary,
  FileRoutes,
  Head,
  Html,
  Meta,
  Routes,
  Scripts,
  Title,
} from 'solid-start';
import Nav from './components/nav';
import './root.css';
import measure from './lib/measure';

export default function Root(): JSX.Element {
  createEffect(() => {
    measure();
  });
  return (
    <Html lang="en">
      <Head>
        <Title>Hacker News Clone</Title>
        <Meta charset="utf-8" />
        <Meta name="viewport" content="width=device-width, initial-scale=1" />
        <Meta name="description" content="Hacker News Clone" />
      </Head>
      <Body>
        <Nav />
        <ErrorBoundary>
          <Suspense fallback={<div class="news-list-nav">Loading...</div>}>
            <Routes>
              <FileRoutes />
            </Routes>
          </Suspense>
        </ErrorBoundary>
        <Scripts />
      </Body>
    </Html>
  );
}

// frameworks/qwikcity/src/root.tsx
import { component$, useVisibleTask$ } from '@builder.io/qwik';
import {
  QwikCityProvider,
  RouterOutlet,
} from '@builder.io/qwik-city';

import './root.css';
import Nav from './components/Nav';
import measure from './lib/measure';

export default component$(() => {
  /**
   * The root of a QwikCity site always start with the <QwikCityProvider> component,
   * immediately followed by the document's <head> and <body>.
   *
   * Don't remove the `<head>` and `<body>` elements.
   */
  useVisibleTask$(() => {
    measure();
  });
  return (
    <QwikCityProvider>
      <head>
        <title>Hacker News Clone</title>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Hacker News Clone" />
      </head>
      <body lang="en">
        <Nav />
        <RouterOutlet />
      </body>
    </QwikCityProvider>
  );
});
