// frameworks/next-app/app/users/[id]/page.tsx
import type { JSX } from 'react';
import fetchAPI from '../../../lib/api';

interface IUser {
  error: string;
  id: string;
  created: string;
  karma: number;
  about: string;
}

async function User({ params }: { params: { id: string } }): Promise<JSX.Element> {
  const user = await fetchAPI<IUser>(`user/${params.id}`);
  return (
    <div className="user-view">
      {
        user.error
          ? <h1>User not found.</h1>
          : (
            <>
              <h1>
                User :
                {' '}
                {user.id}
              </h1>
              <ul className="meta">
                <li>
                  <span className="label">Created:</span>
                  {' '}
                  {user.created}
                </li>
                <li>
                  <span className="label">Karma:</span>
                  {' '}
                  {user.karma}
                </li>
                {!!user.about && (
                <>
                  <li dangerouslySetInnerHTML={{ __html: user.about }} className="about" />
                  {' '}
                </>
                )}
              </ul>
              <p className="links">
                <a href={`https://news.ycombinator.com/submitted?id=${user.id}`}>
                  submissions
                </a>
                {' '}
                |
                {' '}
                <a href={`https://news.ycombinator.com/threads?id=${user.id}`}>
                  comments
                </a>
              </p>
            </>
          )
      }
    </div>
  );
}

export default User;

// frameworks/qwikcity/src/routes/users/[id]/index.tsx
import { component$ } from '@builder.io/qwik';
import fetchAPI from '../../../lib/api';
import { routeLoader$ } from '@builder.io/qwik-city';

interface IUser {
  error: string;
  id: string;
  created: string;
  karma: number;
  about: string;
}

export const useData = routeLoader$(async (event) => (
  fetchAPI<IUser>(`user/${event.params.id}`)
));

export default component$(() => {
  const user = useData();
  return (
    
    <div class="user-view">
      {
        user.value.error
          ? <h1>User not found.</h1>
          : (
            <>
              <h1>
                User :
                {' '}
                {user.value.id}
              </h1>
              <ul class="meta">
                <li>
                  <span class="label">Created:</span>
                  {' '}
                  {user.value.created}
                </li>
                <li>
                  <span class="label">Karma:</span>
                  {' '}
                  {user.value.karma}
                </li>
                {!!user.value.about && (
                <>
                  <li dangerouslySetInnerHTML={user.value.about} class="about" />
                  {' '}
                </>
                )}
              </ul>
              <p class="links">
                <a href={`https://news.ycombinator.com/submitted?id=${user.value.id}`}>
                  submissions
                </a>
                {' '}
                |
                {' '}
                <a href={`https://news.ycombinator.com/threads?id=${user.value.id}`}>
                  comments
                </a>
              </p>
            </>
          )
      }
    </div>
  );
});
