// frameworks/solid-start/src/components/comment.tsx
import type { JSX } from 'solid-js';
import { For, Show } from 'solid-js';
import { A } from 'solid-start';
import type { IComment } from '~/types';
import Toggle from './toggle';

function Comment(props: { comment: IComment }): JSX.Element {
  return (
    <li class="comment">
      <div class="by">
        <A href={`/users/${props.comment.user}`}>{props.comment.user}</A>
        {' '}
        {props.comment.time_ago}
        {' '}
        ago
      </div>
      <div class="text" innerHTML={props.comment.content} />
      <Show when={props.comment.comments.length}>
        <Toggle>
          <For each={props.comment.comments}>
            {(comment): JSX.Element => <Comment comment={comment} />}
          </For>
        </Toggle>
      </Show>
    </li>
  );
}

export default Comment;

// frameworks/next-app/components/Comment.tsx
import type { JSX } from 'react';
import Link from 'next/link';
import type { IComment } from './types';
import Toggle from './Toggle';

export default function Comment({ comment }: { comment: IComment }): JSX.Element {
  return (
    <li className="comment">
      <div className="by">
        <Link href={`/users/${comment.user}`}>{comment.user}</Link>
        {' '}
        {comment.time_ago}
        {' '}
        ago
      </div>
      <div
        className="text"
        dangerouslySetInnerHTML={{
          __html: comment.content,
        }}
      />
      {!!comment.comments.length && (
        <Toggle>
          {comment.comments.map((cmt) => <Comment key={cmt.id} comment={cmt} />)}
        </Toggle>
      )}
    </li>
  );
}
