// frameworks/solid-start/src/components/story.tsx
import type { JSX } from 'solid-js';
import { Show } from 'solid-js';
import { A } from 'solid-start';

import type { IStory } from '../types';

function Story(props: { story: IStory }): JSX.Element {
  return (
    <li class="news-item">
      <span class="score">{props.story.points}</span>
      <span class="title">
        <Show
          when={props.story.url}
          fallback={<A href={`/item/${props.story.id}`}>{props.story.title}</A>}
        >
          <a href={props.story.url} target="_blank" rel="noreferrer">
            {props.story.title}
          </a>
          <span class="host">
            {' '}
            (
            {props.story.domain}
            )
          </span>
        </Show>
      </span>
      <br />
      <span class="meta">
        <Show
          when={props.story.type !== 'job'}
          fallback={
            <A href={`/stories/${props.story.id}`}>{props.story.time_ago}</A>
            }
        >
          by
          {' '}
          <A href={`/users/${props.story.user}`}>{props.story.user}</A>
          {' '}
          {props.story.time_ago}
          {' '}
          |
          {' '}
          <A href={`/stories/${props.story.id}`}>
            {props.story.comments_count
              ? `${props.story.comments_count} comments`
              : 'discuss'}
          </A>
        </Show>
      </span>
      <Show when={props.story.type !== 'link'}>
        {' '}
        <span class="label">{props.story.type}</span>
      </Show>
    </li>
  );
}

export default Story;

// frameworks/next-app/components/Story.tsx
import type { JSX } from 'react';

import type { IStory } from './types';
import Link from 'next/link';

function Story({ story }: { story: IStory }): JSX.Element {
  return (
    <li className="news-item">
      <span className="score">{story.points}</span>
      <span className="title">
        {(
          story.url
            ? (
              <>
                <a href={story.url} target="_blank" rel="noreferrer">
                  {story.title}
                </a>
                <span className="host">
                  {' '}
                  (
                  {story.domain}
                  )
                </span>
              </>
            )
            : <Link href={`/item/${story.id}`}>{story.title}</Link>
        )}
      </span>
      <br />
      <span className="meta">
        {(
          story.type !== 'job'
            ? <>
              by
              {' '}
              <Link href={`/users/${story.user}`}>{story.user}</Link>
              {' '}
              {story.time_ago}
              {' '}
              |
              {' '}
              <Link href={`/stories/${story.id}`}>
                {story.comments_count
                  ? `${story.comments_count} comments`
                  : 'discuss'}
              </Link>
            </>
            : <Link href={`/stories/${story.id}`}>{story.time_ago}</Link>
        )}
      </span>
      {story.type !== 'link' && <>
        {' '}
        <span className="label">{story.type}</span>
      </>}
    </li>
  );
}

export default Story;
