// frameworks/next-app/components/Nav.tsx
import Link from 'next/link';
import type { JSX } from 'react';

export default function Nav(): JSX.Element {
  return (
    <header className="header">
      <nav className="inner">
        <Link href="/">
          <strong>HN</strong>
        </Link>
        <Link href="/new">
          <strong>New</strong>
        </Link>
        <Link href="/show">
          <strong>Show</strong>
        </Link>
        <Link href="/ask">
          <strong>Ask</strong>
        </Link>
        <Link href="/job">
          <strong>Jobs</strong>
        </Link>
      </nav>
    </header>
  );
}

// frameworks/solid-start/src/components/nav.tsx
import type { JSX } from 'solid-js';
import { A } from 'solid-start';

export default function Nav(): JSX.Element {
  return (
    <header class="header">
      <nav class="inner">
        <A href="/">
          <strong>HN</strong>
        </A>
        <A href="/new">
          <strong>New</strong>
        </A>
        <A href="/show">
          <strong>Show</strong>
        </A>
        <A href="/ask">
          <strong>Ask</strong>
        </A>
        <A href="/job">
          <strong>Jobs</strong>
        </A>
      </nav>
    </header>
  );
}
